# Generated by Django 4.2.11 on 2024-04-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecommendedDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('category', models.CharField(max_length=50)),
                ('dest_title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('read', models.BooleanField(default=False)),
            ],
        ),
    ]
