# Generated by Django 4.2.11 on 2024-04-05 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_userrecommendeddestination'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrecommendeddestination',
            old_name='dest_title',
            new_name='destination',
        ),
    ]
