# Generated by Django 4.2.11 on 2024-04-06 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_featured_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_on']},
        ),
    ]
