# Generated by Django 4.2.11 on 2024-04-06 14:58

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_aboutsectionnavimage_featured_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareDiscoveryFormBgVid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_video', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
            ],
        ),
    ]
