# Generated by Django 4.2.11 on 2024-04-06 23:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_sharediscoveryformbgvid_featured_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharediscoveryformbgvid',
            name='featured_video',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='video'),
        ),
    ]
