# Generated by Django 4.2.11 on 2024-04-06 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_sharediscoveryformbgvid_featured_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharediscoveryformbgvid',
            name='title',
            field=models.CharField(default='ok', max_length=50),
            preserve_default=False,
        ),
    ]
