# Generated by Django 4.2.11 on 2024-04-17 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecommendeddestination',
            name='category',
            field=models.CharField(),
        ),
    ]
