# Generated by Django 4.2.11 on 2024-04-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_userrecommendeddestination_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.IntegerField(choices=[(0, 'Mountains'), (1, 'Coasts'), (2, 'Lakes'), (3, 'Forests')]),
        ),
    ]
